export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';

export const GET_USER = 'GET_USER';
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_MEAL_BY_ID = 'GET_MEAL_BY_ID';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_AREAS = 'GET_AREAS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';

export const GET_MEALS_BY_CATEGORY_WITH_LIMIT =
	'GET_MEALS_BY_CATEGORY_WITH_LIMIT';
export const GET_MEALS_BY_CATEGORY = 'GET_MEALS_BY_CATEGORY';
export const GET_MEALS_BY_AREA = 'GET_MEALS_BY_AREA';

export const SEARCH_MEAL_BY_NAME = 'SEARCH_MEAL_BY_NAME';
export const SEARCH_MEAL_BY_INGRDIENT = 'SEARCH_MEAL_BY_INGRDIENT';

export const GET_RANDOM_LIST = 'GET_RANDOM_LIST';
export const GET_LATEST_LIST = 'GET_LATEST_LIST';
export const GET_A_RANDOM_MEAL = 'GET_A_RANDOM_MEAL';

export const RESET_SEARCH = 'RESET_SEARCH';
export const SAVE_TO_USER_DB = 'SAVE_TO_USER_DB';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
